tanishaness/SPROCTOR

CONTRIBUTING.md, ReadMe.md
This PR issue no. # 8 introduces a CONTRIBUTING.md file that provides clear sections on code style, writing tests, documentation, and reporting issues. It also modifies the README to redirect users to the new contributing guidelines, enhancing the project's documentation and making it easier for potential contributors to understand how to get involved. These changes aim to improve the onboarding process for new contributors and ensure consistency across the project.
Thank you for assigning me this task! I appreciate the opportunity to contribute to the project and improve its documentation.
=> Add CONTRIBUTING.md and Update README for Better Guidance

ReadMe.md
Fixes  #12 
I have added the Contributors badges at the bottom.
=> Contributors Badges in Read Me

Backend/screen_recorder.py
Hi @tanishaness this is with reference to issue #17 that was assigned to me. I have  made the necessary changes in the code as i have suggested in the issue. Please let me know if there are any problems.
Lastly, your code if very nicely organized and is working perfectly!! You worked hard! Keep Coding!!!
**(P.S.)**:- Please add the **(gssoc-ext)** and **(hacktoberfest)** tags to this pull request
Thanking you,
Yash Vashishth
(Contributor, GSSoC'24(Ext) and Hacktoberfest)
=> feat: bug: Instructed changes on "screen recorder.py"

Backend/graph.py
I have inserted a heap map for better visualization of the graph where the drastic view of change in the data with respect to time can be seen.
https://github.com/user-attachments/assets/24c7106a-1666-4c32-9168-69ff50a4eb30
=> Change the graph for better visualization

Backend/peer_comparison_tool.py
The program allows users to input data for multiple students, calculating their average study hours, participation rates, and assignment completion. It identifies outliers in these metrics and visualizes the results with a bar chart comparing individual student performances to the averages.
key features:-
Data Input, Average Calculation, Outlier Detection, Data Visualization, User-Friendly Output, Interactive Experience
Overall, the tool is designed to help users evaluate and visualize student performance metrics in a comparative manner.
This tool can be using in future video detection. and then generating a bar graph.
Note:- Add all labels added to the issue #9. So that GSSoC team can easily recognize the commit!
=> Adding Peer Comparison Tool.

Backend/audio.py, Backend/detection.py, Backend/face-rec.py, Backend/graph.py, Backend/head_pose.py, Backend/peer_comparison_tool.py, Backend/processes.py, Backend/pyaudio_test.py, Backend/run.py, Backend/screen_recorder.py
**Handling Issue #29** 
This PR introduces the following key changes across all Python files in the project:
- Added appropriate `try-except` blocks to handle potential runtime errors.
- Ensured that specific error messages are logged for easier debugging.
- Simplified complex functions by breaking them into smaller, more readable components.
- Improved variable naming for clarity and consistency.
- Optimized loops and conditions to reduce computational overhead.
- Reduced memory consumption by refactoring certain data handling methods.
All these changes have been made in `Backend`
=> Updated and Handled all python files 

LICENSE, ReadMe.md
=> Added LICENSE

GUI/active.html, GUI/copypaste.html, GUI/windowClose.html
#45 has been added,
@tanishaness can you please review this , thank you!
https://github.com/user-attachments/assets/7812c701-e804-4385-9c06-44921e13f543
=> the multilanguage translator added

Backend/Offline-capabilities/ML-Model-Optimisation.py, Backend/Offline-capabilities/local-storage.py, Backend/Offline-capabilities/processing-data.py, Backend/Offline-capabilities/readme.md, Backend/Offline-capabilities/resource-management.py, Backend/Offline-capabilities/video-processing.py
Solves #36
**Summary:**
This PR introduces the offline proctoring capability to the S-Proctor system, allowing the application to function seamlessly without requiring continuous internet access during exams. This feature addresses the challenge of conducting exams in low-infrastructure areas and ensures that proctoring can continue even with limited or no internet connectivity.
---
1. **Local Data Storage (SQLite):**
- A lightweight local database is used to store behavior logs and cheat probability data when the internet is unavailable.
- All student activity data is saved in SQLite and synced with the server once the connection is restored.
2. **Efficient Video Processing:**
- The video feed is processed efficiently by analyzing only key frames, reducing computational overhead and …
=> Enhancing Offline Capabilities of S-Proctor for Real-Time Cheating Detection

GUI/active.html, GUI/copypaste.html, GUI/windowClose.html, contributor/contributor.css, contributor/contributor.html, contributor/contributor.js
#43 solved.
the contributors page has been added. added a footer aswell.
@tanishaness can you please review this aswell.
https://github.com/user-attachments/assets/4f9e6e7b-1a05-42e9-be72-01029aea3708
=> contributor page added.

Backend/Dataset/feedback.html, GUI/active.html, GUI/copypaste.html, GUI/windowClose.html
Add or update the file and add the feature to make more attractive website
Fixes: #37 
Thank you for the chance
Please review the pull request and approved it and label it level 2
@tanishaness
=> Made the modification

.github/scripts/update_structure.py, .github/workflows/update-readme.yml, PROJECT_STRUCTURE.md, ReadMe.md, repo_structure.txt
=> Automated project structure updation using github workflows, python scripts and action bot

.github/workflows/issue_open_close.yml, .github/workflows/pr_merge.yaml, .github/workflows/pr_raise.yml, .github/workflows/pt_checker.yaml
Closes #54 
1. Auto comment on issue **Closed** and **Opened**
2. Auto comment on **PR mergs**
3. Auto comment on **PR raises**
4. PR issue checker
Using this workflows makes you'r repo more interactive ! @tanishaness 
**Proof**:
**PR merged:**
<br>
**Issue open and close:**
<br>
**pr issue checker**:
_**Note**_: kindly add all the labels added to issue #54. To this PR! and assign me!
=> Github actions for more connectivity!

calenderApp/calender.html
fix: #57 
**Clicking on date in the calender takes you to the google events**
=> Add calender app to the app || Integrated With Google Calender 

ReadMe.md
added Stargazers and Forkers section to readme.md
PR Description
added Stargazers and Forkers section to readme.md
fixes #62 
close #62 
Change
added Stargazers and Forkers section to readme.md
Stargazers
Use Case:
1. Bookmarking Projects
2. Discovering Popularity
Benefits:
1. Visibility
2. Feedback Indicator
3. Community Engagement
Forkers
Use Case:
1. Creating Personal Copies
2. Contributing Back
Benefits:
1. Encouraging Innovation
2. Easy Collaboration
3. Building Ownership
=> Added Stargazers and Forkers section to readme.md

CONTRIBUTING.md
I have enhanced the document and also added some new sections
Done the following changes :-
1) Enhanced the project structure
2) Added code of conduct section
3) Added star our repository section
4) Added need help with the basics section
5) Added the project structure
6) Modified the pull request process section
7) Added additional method of contributing through GitHub desktop section
8) Added help and support section
9) Added good coding practices section
10) Modified the issue report section
Fixes:[#71 ]
Closes:[#71 ]
=> Done the enhancements

Backend/login.py, PROJECT_STRUCTURE.md, Userdb.sql, login.py, repo_structure.txt, templates/login.html
The login page is designed to provide a user-friendly interface for authentication, allowing users to securely enter their credentials, including a username and password. Upon submission, the system verifies the provided details against the database to grant access, while also offering feedback through flash messages that inform users of the login status, whether successful or requiring corrections.
=> Enhancement of login page FIXES #66

__pycache__/tutorial/tutorial.html
This PR adds a "Tutorials" page to provide users with step-by-step guides and video tutorials on using the platform’s features. The page offers categorized tutorials, making it easier for users to learn, explore functionalities, and improve their skills with the application, ultimately enhancing user engagement and support.
=> Add Tutorials Page for Guided Learning and Feature Exploration

Backend/mtcnn_face_detection.py
=> Created the python file for face detection using MTCNN 

calenderApp/calender.html
Created more user-friendly, attractive interface.
Explanation of Changes:
1)Gradient Backgrounds and Button Enhancements: The gradients add depth, while rounded buttons create a modern look.
2)Sidebar Interaction: Transitions and hover effects improve interactivity and focus on current selection.
3)Calendar Grid Animations: Scaling days on hover provides a lively interaction.
4)Stat Card Styling: Vibrant gradient backgrounds make the statistics section more engaging and visually striking.
// Please assign gssoc label
=> Updated calender.html

Backend/audio.py
Description: Currently, the amplitude threshold for detecting sound is hard-coded. Implement a way for users to configure this threshold through an input prompt or command-line argument. This enhancement will allow users to customize the sensitivity of the sound detection to suit their specific needs.
Default - 20 value for Sus Calc
Issue number- #90
Contributor for- Gssoc-ext, Hacktoberfest
=> Configurable Amplitude Threshold #90
